### ISSUE TITLE
Why <handDesc> in the file Siksa Guru is turning red

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#3] opened 2020-03-28 09:05 UTC
Dear Axelle,

I try to put <handDesc> inside TEI Header of <SiksaGuru_L642-diplo> file, but it fails for the validation. So I still record it as commentary. How to resolve it?

Many thanks before.

**Comment by ajaniak** [comment] 2020-03-30 07:15
Dear @aditiagunawan, 

The issue is in 
```
<pb n="15r"/><lb n="15r1" break="no"/>bahu paṅupaḍrava saṁ pandita, ri vkasniṁ I ruh<spaceur, syuḥ gәsiṁ kapr̥vasa, Ika vkәsniṁ I ruhur, ḍe sañjata saṁ pandita, nihan· lvarnya,nikaṁ saṁ
```
What I assume to be a  `<space>` tag isn't closed correctly :`ruh<spaceur` . Can I let you close it so the encoding is still conformant to your intent ? 

I added the <handDesc> from your commentary. Can you check that as well please? 

Best,

**Comment by aditiagunawan** [comment] 2020-03-30 07:32
Thanks, Axelle. Problem resolved.

**Comment by ajaniak** [comment] 2020-03-30 07:33
Great!

**Closed by ajaniak** 2020-03-30 07:33 UTC
